app:
    build: .

    env_file: .env

    environment:
        RAILS_ENV: 'development'

    links:
        - db

    ports:
        - "3000:3000"
db:
    image: postgres:9.6.1

    volumes:
        - codejam-postgres:/var/lib/postgresql/data
